name: 'Github-repo-creation '
on:
  workflow_dispatch:
  push:
    branches:
    - main
  pull_request:

jobs:
  Terraform:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Terrafrom init
      run: |
        ls
        terraform init -backend-config="path=./terraform.tfstate"

    - name: Terrafrom validate
      run: |
        terraform validate
      env:
        TF_VAR_git_token: ${{ secrets.git_token }}

    - name: Terrafrom plan
      run: |
        terraform plan
      env:
        TF_VAR_git_token: ${{ secrets.git_token }}

    - name: Terrafrom apply
      run: |
        terraform destroy --auto-approve
        #terraform apply --auto-approve
      env:
        TF_VAR_git_token: ${{ secrets.git_token }}
