name: 'Github-repo-creation '
on:
  workflow_dispatch:
  push:
    branches:
    - main
  pull_request:

jobs:
  check-links:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Terrafrom init
      run: |
        ls
        terraform init -backend-config="path=./terraform.tfstate"

    - name: Terrafrom validate
      run: |
        terraform validate
